### ISSUE TITLE
ItemID list of spells by expansion

### ISSUE THREAD

**Issue by xackery** [xackery/peq-expansions#1]
You will need to be added as a contributor in order to be able to edit. Comment below and request access, I'll get you in. Once a contributor, you can click the links below and edit the files on github. Use markdown to add entries, it should be quite trivial.

This will be used to affect loot drops, merchantlist, and help us discern quests or spawns that should be disabled. In the notes section put anything you can find, for example if it's used in any quests.

In majority of cases, max expansion is 99. In cases a spell no longer drops, set this to the next logical expansion it should be removed and add a note describing why

* [x] [Bard Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/brd.md)
* [x] [Beastlord Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/bst.md)
* [x] [Berserker Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/ber.md)
* [x] [Cleric Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/clr.md)
* [x] [Druid Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/dru.md)
* [x] [Enchanter Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/enc.md)
* [x] [Magician Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/mag.md)
* [x] [Monk Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/mnk.md)
* [x] [Necromancer Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/nec.md)
* [x] [Paladin Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/pal.md)
* [x] [Ranger Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/rng.md)
* [x] [Rogue Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/rog.md)
* [x] [Shadow Knight Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/shd.md)
* [x] [Shaman Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/shm.md)
* [x] [Warrior Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/war.md)
* [x] [Wizard Spells](https://github.com/xackery/peq-expansions/blob/master/peq/spells/wiz.md)

**Comment by xackery** [comment]
This will affect loot drops and merchantlist, also if you know the item is a quest reward, note it. 
Here's an example:
I went to http://mqemulator.net/spells.php?name=&class=8&minlevel=&maxlevel=&spelleffect=&isearch=Search and 
ItemID|Name|MinExpansion|MaxExpansion|Note|
---|---|---|---|
78750|Aelfric`s Last Lullaby|12|99|
78751|Aelfric`s Last Lullaby Rk II|12|99|
15718|Agilmente's Aria of Eagles|0|99|

**Comment by nathanhicks** [comment]
I'd like to contribute in my spare time.  Can you clarify - is this just transferring that information from the database into Markdown, looking up its item ID, and adding expansion information?

**Comment by xackery** [comment]
@nathanhicks hi nathan!
hmm you can see an example here: https://github.com/xackery/peq-expansions/blob/master/peq/spells/brd.md

Let's use Aelfric's Last Lullaby as an example. We know it released on TSS when we search it on alla:
http://everquest.allakhazam.com/db/item.html?item=51523 
so we set the min field to 12.

then let's search for Agilmente's Aria of Eagles:
original, ok, set min field to 0.

that's all I need for now.

The other details I can do some scripting operations to populate (that's what i did with bard). If you can just help me alla search and get min expansion set

00 Classic 1999
01 The Ruins of Kunark March 2000
02 The Scars of Velious December 2000
03 The Shadows of Luclin December 2001 
04 The Planes of Power October 2002 
05 The Legacy of Ykesha February 2003 
06 Lost Dungeons of Norrath September 2003 
07 Gates of Discord February 2004 
08 Omens of War September 2004 
09 Dragons of Norrath February 2005 
10 Depths of Darkhollow September 2005 
11 Prophecy of Ro February 2006 
12 The Serpent's Spine September 2006 
13 The Buried Sea February 2007 
14 Secrets of Faydwer November 2007 
15 Seeds of Destruction October 2008 
16 Underfoot December 2009 
17 House of Thule October 2010 
18 Veil of Alaris November 2011 
19 Rain of Fear November 2012 
20 Call of the Forsaken October 2013

That's all i'm looking for, for now!

**Comment by nathanhicks** [comment]
Cool - made significant progress on the bard.md for expansion numbers tonight.  Don't have direct write access to those files though, so it's making me do pull requests.

**Comment by nathanhicks** [comment]
I'm tracking there will be some duplicate items in these markdown files I'm posting because there were duplicate instances of those spells in the database.  I'll go through after I finish posting all and clean up as needed.

**Comment by nathanhicks** [comment]
@xackery All classes have expansion information matched to their spells.  Next step is QA/QC for one-off spots where expansion data wasn't available (do a little more digging), and then to tag each spell in the notes whether they're quested.

**Comment by xackery** [comment]
This looks good, going to close as complete. Great job @nathanhicks !
